firstPRMergeComment: >
    Thanks for your first pull request and welcome to the community!
    Feel free to keep them comming!

    Most developers hang out on IRC. So join \#nextcloud-dev on Freenode for a chat!
